In [2]:
import numpy as np
X_AND = np.array([[0,0],
                  [0,1],
                  [1,0],
                  [1,1]])

Y_AND = np.array([[0],
                  [0],
                  [0],
                  [1]])
print(X_AND.shape)
bias = np.ones((X_AND.shape[0],1))
X_AND_with_bias = np.hstack((bias, X_AND))
weights = np.zeros(X_AND_with_bias.shape[1])
threshold = 0
print(weights.shape)
for itr in range(50):
    for x, y in zip(X_AND_with_bias, Y_AND):
        # print(x, y)
        # print(x.shape, weights.shape)
        # print(weights.shape)
        weighted_sum = np.dot(x, weights.T)
        # print(weighted_sum)
        if weighted_sum >= threshold:
            yhat = 1
        else:
            yhat = 0
        if(yhat != y):
            weights = weights + (y - yhat) * x.T
    if(itr%10 == 0):
        print(weights)

print('Use weights of AND perceptron into OR perceptron')


X_OR = np.array([[0,0],
                  [0,1],
                  [1,0],
                  [1,1]])

Y_OR = np.array([ [0],
                  [1],
                  [1],
                  [1]])


print(X_OR.shape)
bias = np.ones((X_OR.shape[0],1))
X_OR_with_bias = np.hstack((bias, X_OR))
# weights = np.zeros(X_OR_with_bias.shape[1])
threshold = 0
print(weights.shape)
print(X_OR_with_bias.shape)
for itr in range(50):
    for x, y in zip(X_OR_with_bias, Y_OR):
        # print(x, y)
        # print(x.shape, weights.shape)
        # print(weights.shape)
        weighted_sum = np.dot(x, weights.T)
        # print(weighted_sum)
        if weighted_sum >= threshold:
            yhat = 1
        else:
            yhat = 0
        if(yhat != y):
            adjustWeightVal = (y - yhat) * x.T
            print(f'adjustWeightVal={adjustWeightVal}')
            weights = weights + adjustWeightVal
    if(itr%10 == 0):
        print(weights)

(4, 2)
(3,)
[0. 1. 1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
Use weights of AND perceptron into OR perceptron
(4, 2)
(3,)
(4, 3)
adjustWeightVal=[1. 0. 1.]
[-2.  2.  2.]
[-2.  2.  2.]
[-2.  2.  2.]
[-2.  2.  2.]
[-2.  2.  2.]
